#!/bin/zsh
# backup configure file

cfLoca="$HOME/.config"
Loca="$HOME/Repo/remote/dotfiles"

#backup i3-wm
cp ${cfLoca}/polybar/my_config ${Loca}/polybar/

#backup i3-wm
cp -r ~/.myScript/* ${Loca}/i3-wm/myScript/
cp ${cfLoca}/i3/config ${Loca}/i3-wm/

#back alacritty
cp ${cfLoca}/alacritty/alacritty.yml ${Loca}/alacritty/alacritty.yml

#backup zsh
cp ~/.zshrc ${Loca}/zsh/zshrc

#backup vim
cp ~/.vimrc ${Loca}/vim/vimrc

#git stone
git add .
git commit -m "`date +%Y-%m-%d`-backup"
